name: Document Pull Request

on:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      PRIVATE_KEY:
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  check-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.55.1

      - id: app-token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - run: github-comment exec -- github-comment hide
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '24'

      - name: Install NPM Packages
        run: npm ci

      - name: Lint Text Files
        run: github-comment exec -k common -var env:Staging -var title:"Check Textlint" -- npm run lint
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Check if Text File is changed
        id: diff
        run: |
          if git diff --exit-code ./articles && git diff --exit-code ./books; then
            # 既存ファイルで変更なし
            echo "changed=0" >> "$GITHUB_OUTPUT"
          else
            # 既存ファイルで変更あり
            echo "changed=1" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and push
        if: steps.diff.outputs.changed == '1'
        uses: suzuki-shunsuke/commit-action@87b297f0ce551411b43d1880f4fb3cbc60381055 # v0.0.14
        with:
          app_id: ${{secrets.APP_ID}}
          app_private_key: ${{ secrets.PRIVATE_KEY }}
          commit_message: "update: Textlint fixes"
          files: |
            articles/*.md
            books/**/*.md

      - name: Install markdownlint
        run: npm install -g markdownlint-cli2

      - name: Lint Markdown Files
        run: github-comment exec -k common-error -var env:Staging -var title:"Check Markdown Failed" -- markdownlint-cli2 "**/*.md" --config ".markdownlint.json"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
